### ISSUE TITLE
03-k8s-进阶篇-01-持久化存储

### ISSUE THREAD

**Issue by little-monster-di** [jettjia/cloud-native#1]
如果想挂载一个nfs的多个目录到不同的目录，需要使用subPath参数，这个也比较常用，作者可以加上，start了已经，期待一起成长
   
volumeMounts:
            # 如果只想使用对应目录下的某个子目录则使用subPath，但是在nfs目录下必须先包含 subPath 的目录
            # 这里只需要定义一个name，定义两个会无法创建成功
            # 比如nfs存储中的nginx配置,log目录,date目录
            - mountPath: /etc/nginx/conf.d
              subPath: nginx/conf
              name: nginx-pvc
            - mountPath: /var/log/nginx
              subPath: nginx/log
              name: nginx-pvc
      volumes:
        - name: nginx-pvc
          persistentVolumeClaim:
            claimName: nginx-pvc

**Comment by jettjia** [comment]
> 如果想挂载一个nfs的多个目录到不同的目录，需要使用subPath参数，这个也比较常用，作者可以加上，start了已经，期待一起成长
> 
> volumeMounts: # 如果只想使用对应目录下的某个子目录则使用subPath，但是在nfs目录下必须先包含 subPath 的目录 # 这里只需要定义一个name，定义两个会无法创建成功 # 比如nfs存储中的nginx配置,log目录,date目录 - mountPath: /etc/nginx/conf.d subPath: nginx/conf name: nginx-pvc - mountPath: /var/log/nginx subPath: nginx/log name: nginx-pvc volumes: - name: nginx-pvc persistentVolumeClaim: claimName: nginx-pvc

嗯，我们之前有些项目用了subPath。后面又全部拿掉了。变成直接指定目录的方式。
